### PR TITLE
chore: update dependencies and runtime version

### PR DESCRIPTION
**Pull request by justinwride**
## ℹ️ About

Updated dependencies and changed runtime version from Node 12 to Node 16.

### CODE REVIEW

**Comment by kevinpainchaud** [comment]
Nice, thanks!

**Comment by joltcoke** [comment]
@justinwride Thank you! 👏 
@JoshCoady Any chance to get this merged?

**Comment by jeffsays** [comment]
bump

**Comment by JoshCoady** [comment]
Merged
sorry it took so long 🙂

**Comment by kevin-leeto** [comment]
Thanks! Can you publish a new release now? :)

**Comment by kevinpainchaud** [comment]
Thanks! Can you publish a new release now? :)

**Comment by bachiri** [comment]
Hi 👋  @JoshCoady where the version 1.0.1 deployed? 

I got this error when trying to get the 1.0.1 version 
`Error: Unable to resolve action LoveToKnow/slackify-markdown-action@v1.0.1, unable to find version v1.0.1`

Thanks

**Comment by JoshCoady** [comment]
Looks like the deploy is broken due to something in an included gh action. I dont currently have time to track this down, but if someone could post a fix, I'll merge it

> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js
> require() of ES modules is not supported.
> require() of /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js from /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/src/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
> Instead rename /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/package.json.

**Comment by bachiri** [comment]
@JoshCoady Just pushed a [PR](https://github.com/LoveToKnow/slackify-markdown-action/pull/10) to fix the issue according [to](https://github.com/cycjimmy/semantic-release-action/issues/143)

**Pull request merged**
