### PR TITLE
feat: Add input variable to stringify result

### LINKED ISSUE #8: Convert the line breaks to Slack \n
Then I pass output of Run LoveToKnow/slackify-markdown-action@v1.0.0 to the slackapi/slack-github-action@v1.24.0, I can have error "passed in payload was invalid JSON".

 _I think Slack is breaking on '%0A', expecting text "\\n"._

> [Line breaks](https://api.slack.com/reference/surfaces/formatting#basics) 
> You can use multi-line text in app-generated text. Insert a newline by including the string \n in your text. For example:
> `This is a line of text.\nAnd this is another one.`

Example text input should be any line break containing.

```log
##[debug]..Evaluating String:
##[debug]..=> 'message'
##[debug]=> '**Your Huma server API is ready to use.✅**
##[debug]
##[debug]Huma server API links:
##[debug]
```

`::set-output name=text::​*Your Huma server API is ready to use.✅*​%0A%0AHuma server API links:%0A`

My part of Github workflow:

```yaml
    - id: convertTextSlackReady
      if: steps.install.outputs.error == 0 &&  steps.restore.outputs.error == 0
      uses: LoveToKnow/slackify-markdown-action@v1.0.0
      with:
        text: ${{ steps.readyMessage.outputs.message }}

    - name: Slack links list
      if: steps.install.outputs.error == 0 &&  steps.restore.outputs.error == 0
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: ${{ inputs.slack_channel_id }}
        payload: |
          {
            "text": "Your server API is ready to use.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ steps.convertTextSlackReady.outputs.text }}"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
```

### PR DESCRIPTION
**Pull request by hasier**
## ℹ️ About

First of all, thanks for building this very handy action! 🙇 

While adding it to our workflows, I realised I couldn't fully use it correctly due to the way newlines are encoded in the output. Similar to what @bachiri [reported](https://github.com/LoveToKnow/slackify-markdown-action/pull/12/files#r1310488091), I am not sure just replacing the newlines as introduced in #9 does the job. There are other characters that could interfere with the JSON format, so I guess the more robust option would be to `JSON.stringify()` the output. This should make sure `\n` is encoded as necessary, as well as any other character.

Let me know your thoughts!

I've also bumped the version string in the lockfiles to `1.1.0`, let me know if you'd rather have a different numbering.

---

- [ ] Has 🧪 tests
- [x] Has 📖 documentation

Fixes #8

### CODE REVIEW

**Comment by hasier** [comment]
@JoshCoady sorry for the direct ping, I saw you merged #9 and I was wondering if you might be the right person to look into this one too 🙂

**Comment by justinwride** [comment]
@hasier I am experiencing a problem since version 1.0.2 where I'm seeing literal `\n` in Slack messages when they were newlines before. I reverted back to 1.0.1 to fix this issue, but would like to see newline characters work as actual newlines in Slack.

**Comment by hasier** [comment]
> @hasier I am experiencing a problem since version 1.0.2 where I'm seeing literal `\n` in Slack messages when they were newlines before. I reverted back to 1.0.1 to fix this issue, but would like to see newline characters work as actual newlines in Slack.

@justinwride that was my issue too, I had to pin back to 1.0.1 as well, then added a tiny workaround similar to the one I proposed here as our payload was slightly more complex and was breaking the encoding in some other ways.

```yml
      - name: Transform markdown into Slack format
        id: transform
        # pin to 1.0.1 as they later changed the string output format
        # https://github.com/LoveToKnow/slackify-markdown-action/pull/12/files#r1310488091
        uses: LoveToKnow/slackify-markdown-action@v1.0.1
        with:
          text: ${{ github.event.release.body }}

      - name: Build Slack payload
        id: build
        uses: actions/github-script@v7
        env:
          BODY: ${{ steps.transform.outputs.text }}
        with:
          script: |
            // Dump the contents to a JSON string as {"text": "..."}
            core.setOutput('payload', JSON.stringify({text: process.env['BODY']}));

      - name: Send payload to Slack
        id: slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: ${{ steps.build.outputs.payload }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
```

**Comment by VincentLanglet** [comment]
Hi, I proposed https://github.com/LoveToKnow/slackify-markdown-action/pull/16 to revert the breaking change on the new line. You can now use 1.1.1.

`toJSON` can be used manually in the actions, example
```
{
                                    "type": "section",
                                    "text": {
                                        "type": "mrkdwn",
                                        "text": ${{ toJSON(steps.changelog.outputs.text) }}
                                    }
                                }
```
but this PR is still interesting because it could add natively the JSON encoding.

You might need to rebase master @hasier

**Comment by hasier** [comment]
Thanks @VincentLanglet! Seems simple enough to use with `toJSON()`. I used the following payload instead, as I am using incoming webhooks.
```
{
    "text": ${{ toJSON(steps.changelog.outputs.text) }}
}
```

These changes feel less useful now, so I am closing this PR.

**Pull request closed without merging**
